apiVersion: v1
kind: Service
metadata:
  name: unimanga-backend
  namespace: default
  labels:
    app: unimanga-backend
spec:
  type: NodePort
  selector:
    app: unimanga-backend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
    protocol: TCP
    name: http
